services:
  - type: web
    name: article-pdf-generator
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
